// <copyright file="Emitter.cs" company="Canon Europe Limited">
// Copyright (c) Canon Europe Limited. All rights reserved.
// </copyright>

namespace EFCore.JsonColumn;

using System.Collections.Generic;
using System.Linq;
using System.Text;

internal static class Emitter
{
    public const string AttributeSource =
        """
        // <auto-generated by Swevo.EFCore.JsonColumn/>
        #nullable enable
        namespace EFCore.JsonColumn;

        /// <summary>Marks a navigation property for EF Core 8+ JSON column configuration.</summary>
        [System.AttributeUsage(System.AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
        public sealed class JsonColumnAttribute : System.Attribute { }
        """;

    public static string EmitCore(IReadOnlyCollection<JsonColumnPropertyModel> properties)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by Swevo.EFCore.JsonColumn/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using Microsoft.EntityFrameworkCore;");
        builder.AppendLine();
        builder.AppendLine("namespace EFCore.JsonColumn;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Extension methods for configuring EF Core JSON-owned navigations marked with <see cref=\"JsonColumnAttribute\"/>.</summary>");
        builder.AppendLine("public static class JsonColumnModelBuilderExtensions");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Configures all properties marked with <see cref=\"JsonColumnAttribute\"/> as JSON-owned navigations.</summary>");
        builder.AppendLine("    public static ModelBuilder ConfigureJsonColumns(this ModelBuilder modelBuilder)");
        builder.AppendLine("    {");

        var orderedProperties = properties
            .OrderBy(static property => property.ContainingTypeName, System.StringComparer.Ordinal)
            .ThenBy(static property => property.PropertyName, System.StringComparer.Ordinal)
            .ToList();

        if (orderedProperties.Count == 0)
        {
            builder.AppendLine("        return modelBuilder;");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        foreach (var group in orderedProperties.GroupBy(static property => property.ContainingTypeName, System.StringComparer.Ordinal))
        {
            builder.Append("        modelBuilder.Entity<");
            builder.Append(group.Key);
            builder.AppendLine(">(entity =>");
            builder.AppendLine("        {");

            foreach (var property in group)
            {
                builder.Append("            entity.OwnsOne(e => e.");
                builder.Append(property.PropertyName);
                builder.AppendLine(", b => b.ToJson());");
            }

            builder.AppendLine("        });");
        }

        builder.AppendLine("        return modelBuilder;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
